// <copyright file="TestStep.cs" company="Infosys Ltd.">
//  Copyright (c) Infosys Ltd. All rights reserved.
// </copyright>
// <summary>TestStep.cs class handles test steps data.</summary>
// <auto-generated />
namespace INF.Selenium.TestAutomation.Entities
{
    using System.Collections;
    using System.Collections.Generic;

    public class TestStep : CollectionBase
    {
        public string TestStepNumber { get; set; }

        public string Action { get; set; }

        public UiControl UiControl { get; set; }

        public Verification Verification { get; set; }

        public string TestDataKeyToUse { get; set; }

        public Dictionary<int, string> TestData { get; set; }

        public string Remarks { get; set; }
    }
}
