// <copyright file="TestResult.cs" company="Infosys Ltd.">
//  Copyright (c) Infosys Ltd. All rights reserved.
// </copyright>
// <summary>TestResult.cs class handles test results preparation.</summary>
// <auto-generated />
namespace INF.Selenium.TestAutomation.Entities
{
    public class TestResult
    {
        public string TestDataIterationNr { get; set; }

        public string StepNr { get; set; }

        public string Description { get; set; }

        public string Result { get; set; }

        public string Comment { get; set; }

        public string Remarks { get; set; }
    }
}