// <copyright file="UIControl.cs" company="Infosys Ltd.">
//  Copyright (c) Infosys Ltd. All rights reserved.
// </copyright>
// <summary>UIControl.cs class handles User interface control data.</summary>
// <auto-generated />
namespace INF.Selenium.TestAutomation.Entities
{
    using System.Collections;

    public class UiControl : CollectionBase
    {
        public string UiControlId { get; set; }

        public string UiControlType { get; set; }

        public string UiControlSearchProperty { get; set; }

        public string UiControlSearchValue { get; set; }
    }
}