// <copyright file="Verification.cs" company="Infosys Ltd.">
//  Copyright (c) Infosys Ltd. All rights reserved.
// </copyright>
// <summary>Verification.cs class handles Verifications data.</summary>
// <auto-generated />
namespace INF.Selenium.TestAutomation.Entities
{
    using System.Collections;

    public class Verification : CollectionBase
    {
        public string VerificationId { get; set; }

        public string VerificationType { get; set; }

        public string OperatorToUse { get; set; }
    }
}
